version: '3.3'

services:
  db:
    image: mysql:5.7.27
    container_name: mysql
    volumes:
      - db_data:/var/lib/mysql
      - ./withparadox2_docker.sql:/docker-entrypoint-initdb.d/dump.sql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: withpara_blog
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress:
    depends_on:
      - db
    image: wordpress:5.4.1
    container_name: wordpress
    ports:
      - '8000:80'
    volumes: 
      - ./wp-content/:/var/www/html/wp-content
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: withpara_blog

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin:4.9.1
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
      PMA_USER: wordpress
      PMA_PASSWORD: wordpress
    restart: always
    ports:
      - 8080:80
    volumes:
      - /sessions

volumes:
  db_data: {}